### ISSUE TITLE
Is it possible to add  kubeflow into edge 

### ISSUE THREAD

**Issue by atzeng** [itrix-edge/ITRIX-Edge#22]
**What would you like to be added/modified**:

**Why is this needed**:
Pipeline can be very useful feature.   Is it possible to add Kubeflow into this ?

**Comment by stevennick** [comment]
We do not plan to support run Kubeflow inside the edge appliance (although it may run without any problems), instead of this, we'll put kfserving support for this Edge project, and Kubeflow can use the Edge appliance as inference or pipeline target.
