### ISSUE TITLE
 Does the Edge cluster require API Gateway?

### ISSUE THREAD

**Issue by DavidKan1993** [itrix-edge/ITRIX-Edge#23]
**What would you like to be added/modified**:
Does the Edge cluster require API Gateway?  How to use API Gateway in Edge cluster?
**Why is this needed**:
API Gateway manages, delivers, and secures enterprise APIs, applications, and consumers. 
API Gateway provide API to each client. It may also have other functions such as authorization, monitoring, load balancing, caching, request sharding and management, and static response processing.

**Comment by stevennick** [comment]
It may require a Gateway or similar capabilities parts inside the edge appliance, but the component location needs to be determined.
