### ISSUE TITLE
itri-edge environmental requirements ?

### ISSUE THREAD

**Issue by momobin** [itrix-edge/ITRIX-Edge#26]
1. OS specifications centos or ubuntu ..... ?
2. The number of networks, one network card or two, do you need Internet_IP ?
3. Hard drive capacity ?

**Comment by stevennick** [comment]
Currently, the project on L4T target; this means we only have ubuntu available now. It still possible to run an edge stack on different OS, but it still needs to be tested.
Compute node will attach the internal networking, and internal static IP behind the router.
